### ISSUE TITLE
how to get ios package name 

### ISSUE THREAD

**Issue by shahzaib2023rnssol** [yash-garg/AppCheck#10]
because for ios use package name like ("calshow://") so how i can get this type package name for different apps . i only check app is installed or not in ios device

**Comment by yash-garg** [comment]
https://stackoverflow.com/a/51650912

**Comment by philipvrx** [comment]
https://support.apple.com/en-vn/guide/deployment/depece748c41/web
It's not working like it should be @Yash-Garg
