### ISSUE TITLE
Problems to recognize APP in IOS

### ISSUE THREAD

**Issue by fumatamax** [yash-garg/AppCheck#11]
Good I am having a problem and is that in iOS, when you check if there is for example the following application "com.myapp.testing" always fails or does not recognize the packageName. But instead when I take the example you provide for iOS. It does open the calendar and recognizes the applications but when you specify a specific package name it does not seem to recognize or locate the application installed on the emulator. I am using the following examples and none of them work correctly do you know how to solve it?

**Comment by yash-garg** [comment]
I've updated some part of the code and also added [instructions here](https://github.com/Yash-Garg/AppCheck#ios), can you try using the latest version and let me know if it works?
