### ISSUE TITLE
Remove QUERY_ALL_PACKAGES permission

### ISSUE THREAD

**Issue by DominikAbOQ** [yash-garg/AppCheck#2]
From **12.07.2022** apps from the PlayStore may be removed , which use the permission QUERY_ALL_PACKAGES without explanation.
Since I only want to check if a certain app is installed, I don't really need this permission.

If you know the packageName you can enter the following in the AndroidManifest.xml and it works without the QUERY_ALL_PACKAGES permission.
```
<queries>
        <package android:name="com._._"/>
        <package android:name="com.google.android.apps.maps"/>
</queries>
```

If you want to check all installed apps, you have to add the permission QUERY_ALL_PACKAGES.
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

But every user of this package should be responsible for the permissions himself.

Could you please check this?

#3

**Comment by yash-garg** [comment]
Thanks for the PR! Will update the package on pub.dev also.
