### ISSUE TITLE
AppCheck.checkAvailability(package) not working. Throwing Unhandled Exception!

### ISSUE THREAD

**Issue by YarosMallorca** [yash-garg/AppCheck#4]
My Code (placed on button):
```
onTap: () async {
  const package =
      "org.codeclickers.universalconverter";
  if (Platform.isAndroid) {
    await AppCheck.checkAvailability(
            package)
        .then(
      (app) => debugPrint(app.toString()),
    );
  }
}
```

Here is the error thrown in terminal:

```
E/getAppPackageInfo (org.codeclickers.universalconverter)( 5580): org.codeclickers.universalconverter
E/flutter ( 5580): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(400, App not found org.codeclickers.universalconverter, null, null)
E/flutter ( 5580): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter ( 5580): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter ( 5580): <asynchronous suspension>
E/flutter ( 5580): #2      AppCheck.checkAvailability
package:appcheck/appcheck.dart:46
E/flutter ( 5580): <asynchronous suspension>
E/flutter ( 5580): #3      _OtherTabState.build.<anonymous closure>.<anonymous closure>
package:tools/tabs/other.dart:68
E/flutter ( 5580): <asynchronous suspension>
E/flutter ( 5580):
```

**Comment by yash-garg** [comment]
The method `checkAvailability()` returns a type of `Future<AppInfo?>`, so you need to add a check for it being `null` (which is probably the case here).

If the result i.e. `app` is `null` then show the user that it doesn't exist on the device else just display the details using the model.

**Comment by YarosMallorca** [comment]
@Yash-Garg I don't think this is the problem here.
Because just `await AppCheck.checkAvailability("org.codeclickers.universalconverter");` already throws `Unhandled Exception`

**Comment by yash-garg** [comment]
It throws a `PlatformException` through the method if app isn't found, you need to handle it.

https://github.com/Yash-Garg/AppCheck/blob/0b5dd3bc30fb80f8815331d66502e8c5921e6683/lib/appcheck.dart#L38-L39

You can use the [`catchError()`](https://dart.dev/guides/libraries/futures-error-handling#catcherror-as-a-comprehensive-error-handler) block also to handle it.
